In [4]:
import tensorflow as tf
import numpy as np

# The 'Hello World' of neural networks

In [3]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1])
])
model.compile(
    optimizer='sgd',
    loss='mean_squared_error'
)

In [5]:
xs = np.array([-1.0, 0.0, 1., 2., 3., 4.], dtype=np.float)
ys = np.array([-3.0, -1., 1., 3., 5., 7.], dtype=np.float)

/var/folders/wr/cy7q4r6d4jz9c6t208k_b19r0000gn/T/ipykernel_77498/233001526.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  xs = np.array([-1.0, 0.0, 1., 2., 3., 4.], dtype=np.float)
/var/folders/wr/cy7q4r6d4jz9c6t208k_b19r0000gn/T/ipykernel_77498/233001526.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ys = np.array([-3.0, -1., 1

In [7]:
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 6ms/step - loss: 0.3583
Epoch 2/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3509
Epoch 3/500
1/1 [==============================] - 0s 6ms/step - loss: 0.3437
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3366
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3297
Epoch 6/500
1/1 [==============================] - 0s 6ms/step - loss: 0.3230
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 0.3163
Epoch 8/500
1/1 [==============================] - 0s 6ms/step - loss: 0.3098
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 0.3035
Epoch 10/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2972
Epoch 11/500
1/1 [==============================] - 0s 5ms/step - loss: 0.2911
Epoch 12/500
1/1 [==============================] - 0s 4ms/step - loss: 0.2851
Epoch 13/500
1/1 [==============================] - 0s 6ms/st

In [8]:
model.predict([10.0])

1/1 [==============================] - 0s 109ms/step


array([[18.990154]], dtype=float32)

In [9]:
model.predict([0])

1/1 [==============================] - 0s 81ms/step


array([[-0.9955759]], dtype=float32)

In [10]:
model.predict([1])

1/1 [==============================] - 0s 43ms/step


array([[1.0029972]], dtype=float32)

# From rules to data